# Generated by Django 2.1.5 on 2019-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190205_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='static/none.png', upload_to='static/'),
        ),
    ]
